article_module/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('articles-by-category/<str:category>', views.ArticleListView.as_view(), name='articles-by-category'),
    path('articles-list/', views.ArticleListView.as_view(), name='article-list-page'),
    path('detials/<article_id>', views.article_detail, name='article-detail-page'),
    path('add-to-favorites', views.add_to_favorite, name='add-to-favorites'),
    path('remove-from-favorites', views.remove_from_favorite, name='remove-from-favorites'),
]

journey/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from journey import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_module.urls')),
    path('', include('about_module.urls')),
    path('', include('user_module.urls')),
    path('', include('article_module.urls')),
    path('', include('contact_module.urls')),
    path('', include('profile_module.urls')),
    path('', include('post_module.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article_module/models.py
from django.db import models
from user_module.models import User


class ArticleCategory(models.Model):
    title = models.CharField(max_length=100)
    # parent = models.ForeignKey('ArticleCategory', null=True, blank=True, on_delete=models.CASCADE)
    url_title = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class Article(models.Model):
    title = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    reading_duration = models.IntegerField()
    image = models.ImageField(upload_to='articles_pic', null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='article_author')
    short_description = models.CharField(max_length=100)
    text = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    slug = models.SlugField(null=True)
    categories = models.ManyToManyField(ArticleCategory)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class ArticleComments(models.Model):
    # parent = models.ForeignKey('ArticleComments', on_delete=models.CASCADE, null=True, blank=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='article_comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now=True)
    display = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user} has left a comment for {self.article.title}'

article_module/forms.py
from django import forms
from article_module.models import ArticleComments, Article


class CreateNewArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'city', 'reading_duration', 'categories', 'short_description', 'slug', 'text', 'image']


class EditArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'city', 'reading_duration', 'categories', 'short_description', 'slug', 'text', 'image']


class ArticleCommentModelForm(forms.ModelForm):
    class Meta:
        model = ArticleComments
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'class': 'form-control bg-transparent',
                                                 'placeholder': 'write your comment here...'})}

article_module/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.views.generic import ListView, FormView
from profile_module.models import Profile
from .forms import ArticleCommentModelForm, CreateNewArticleForm, EditArticleForm
from .models import Article, ArticleCategory, ArticleComments
from braces import views


class ArticleListView(ListView):
    template_name = 'article-list.html'
    model = Article

    def get_queryset(self):
        query = super(ArticleListView, self).get_queryset()
        category = self.kwargs.get('category')
        if category is not None:
            query = query.filter(is_active=True, categories__url_title__iexact=category)
        return query

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        category = self.kwargs.get('category')
        context['cat'] = category
        return context


def article_detail(request, article_id):
    # article details and comments (the GET part)
    article: Article = get_object_or_404(Article, id=article_id, is_active=True)
    display_true_comments = ArticleComments.objects.filter(display=True, article_id=article_id).all()
    comment_form = ArticleCommentModelForm()

    # comment form section (the POST part)
    if request.method == "POST":
        comment_form = ArticleCommentModelForm(request.POST)
        if comment_form.is_valid():
            new_comment: ArticleComments = comment_form.save(commit=False)
            new_comment.user_id = request.user.id
            new_comment.article_id = article_id
            new_comment.save()
            return HttpResponseRedirect(article_id, 'article-detail-page')
    context = {'article': article, 'comment_form': comment_form, 'display_true_comments': display_true_comments}
    return render(request, 'article-details.html', context)


# render a component in article-list-page and articles-by-category
def article_category_component(request):
    main_categories = ArticleCategory.objects.filter(is_active=True).order_by('title')
    return render(request, 'components/article-category-component.html', {'main_categories': main_categories})


@login_required
def add_to_favorite(request):
    article_id = request.POST.get('article_id')
    try:  # if profile and article do exist , then add that article in user profile's saved_articles
        profile = Profile.objects.get(user_id=request.user.id)
        article = Article.objects.get(id=article_id)
        profile.saved_articles.add(article)
        return JsonResponse({'success': 'the article has been added to your favorite list.'})
    except Profile.DoesNotExist:
        return JsonResponse({'error': 'the profile does not exists.'})
    except Article.DoesNotExist:
        return JsonResponse({'error': 'the article does not exists.'})


@login_required
def remove_from_favorite(request):
    article_id = request.GET.get('article_id')
    try:
        profile = Profile.objects.get(user_id=request.user.id)
        article = Article.objects.get(id=article_id)
        profile.saved_articles.remove(article)
        return JsonResponse({'success': True})
    except:  # should I use DoesNotExist ?
        return JsonResponse({'success': False})


class NewArticleView(views.StaffuserRequiredMixin, FormView):  # usage : profile_module / in staff part
    form_class = CreateNewArticleForm
    template_name = 'staff/new-article.html'
    success_url = '/all-articles'

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.save()
        return super().form_valid(form)


class AllArticlesView(views.StaffuserRequiredMixin, ListView):  # usage : profile_module / in staff part
    template_name = 'staff/all-articles.html'
    model = Article
    paginate_by = 3


class EditArticleView(views.StaffuserRequiredMixin, View):  # usage : profile_module / in staff part
    def get(self, request, pk):
        article = get_object_or_404(Article, id=pk)
        form = EditArticleForm(instance=article)
        return render(request, 'staff/edit-article.html', {'form': form, 'article': article})

    def post(self, request, pk):
        article = get_object_or_404(Article, id=pk)
        form = EditArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
        return render(request, 'staff/edit-article.html', {'form': form, 'article': article})


@staff_member_required
def delete_article(request, pk):  # usage : profile_module / in staff part
    article = get_object_or_404(Article, id=pk)
    article.delete()
    return redirect('articles-page')


class DisplayCommentsView(views.StaffuserRequiredMixin, View):  # usage : profile_module / in staff part
    def get(self, request, pk):
        comments = ArticleComments.objects.filter(article_id=pk)
        return render(request, 'staff/display-comments.html', {'comments': comments})

    def post(self, request, pk):
        comments = ArticleComments.objects.filter(article_id=pk)
        for comment in comments:
            display_list = request.POST.get(str(comment.id)) == 'on'  # a list of checked items
            comment.display = display_list  # if the item has checked , then set the item's display "True".
            comment.save()
        return render(request, 'staff/display-comments.html', {'comments': comments})

article_module/templates/article-details.html
{% extends 'base.html' %}
{% load render_partial %}
{% load thumbnail %}

{% block title %}article details{% endblock %}

{% block content %}
    <!-- article detail start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="row g-5">
                <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.1s"
                     style="min-height: 400px; visibility: visible; animation-delay: 0.1s; animation-name: fadeInUp;">
                    <div class="position-relative h-100">
                        {% thumbnail article.image "600x400" crop="center" as im %}
                            <img class="img-fluid position-absolute" src="{{ im.url }}" alt="">
                        {% endthumbnail %}
                    </div>
                </div>
                <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.3s"
                     style="visibility: visible; animation-delay: 0.3s; animation-name: fadeInUp;">
                    <h6><a href="{% url 'user-info' article.author.username %}"
                           class="section-title bg-white text-start text-primary pe-3">by
                        : {{ article.author.username }}</a></h6>
                    <h1 class="mb-4">{{ article.title }}</h1>
                    <p class="mb-4">{{ article.text }}</p>
                    <p class="mb-4">yep</p>
                </div>
            </div>
        </div>
    </div>
    <!-- article detail end -->

    <!-- display comments start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Comments</h6>
                <h1 class="mb-5">Leave your comments down here</h1>
            </div>
            <div class="row g-4">
                {% for comment in display_true_comments %}
                    <a href="{% url 'user-info' comment.user.username %}">
                        <div class="col-lg-12 col-sm-12 wow fadeInUp" data-wow-delay="0.3s">
                            <div class="service-item rounded pt-3">
                                <div class="p-4">
                                    <strong style="color: darkolivegreen">From : {{ comment.user.username }}</strong>
                                    <p style="color: gray">{{ comment.text }}</p>
                                </div>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- display comments end -->

    <!-- comment form start -->
    {% if request.user.is_authenticated %}
        {% include 'components/article-comments.html' %}
    {% else %}
        <div class="container-xxl py-5">
            <div class="container">
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h6 class="section-title bg-white text-center text-primary px-3">notice</h6>
                </div>
                <h6 class="text-center">to leave comments you must be <a href="{% url 'login-page' %}">logged in</a>.
                </h6>
            </div>
        </div>
    {% endif %}
    <!-- comment form end -->
{% endblock %}

article_module/templates/article-list.html
{% extends 'base.html' %}
{% load render_partial %}
{% load thumbnail %}

{% block title %}articles{% endblock %}
{% block content %}
    <div class="container-xxl py-5">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s"
                 style="visibility: visible; animation-delay: 0.1s; animation-name: fadeInUp;">
                <h6 class="section-title bg-white text-center text-primary px-3">all articles</h6>
                <h1 class="mb-5">How much do you know about your favorite country?</h1>
            </div>
            <!-- categories start -->
            {% render_partial 'article_module.views.article_category_component' %}
            <!-- categories end -->
            <br>
            <!-- articles list start -->
            <div class="row g-4 justify-content-center">
                {% for article in article_list %}
                    <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s"
                         style="visibility: visible; animation-delay: 0.1s; animation-name: fadeInUp;">
                        <div class="package-item">
                            <div class="overflow-hidden">
                                {% thumbnail article.image "400x300" crop="center" as im %}
                                    <img class="img-fluid" src="{{ im.url }}" alt="">
                                {% endthumbnail %}
                            </div>
                            <div class="d-flex border-bottom">
                                <small class="flex-fill text-center border-end py-2"><i
                                        class="fa fa-map-marker-alt text-primary me-2"></i>{{ article.city }}</small>
                                <small class="flex-fill text-center border-end py-2"><i
                                        class="fa fa-calendar-alt text-primary me-2"></i>{{ article.create_date }}
                                </small>
                                <small class="flex-fill text-center py-2"><a
                                        href="{% url 'user-info' article.author.username %}"><i
                                        class="fa fa-user text-primary me-2"></i>{{ article.author.username }}
                                </a></small>
                            </div>
                            <div class="text-center p-4">
                                <h3 class="mb-0">{{ article.title }}</h3>
                                <div class="mb-3">
                                    <small class="fa fa-star text-primary"></small>
                                    <small class="fa fa-star text-primary"></small>
                                    <small class="fa fa-star text-primary"></small>
                                    <small class="fa fa-star text-primary"></small>
                                    <small class="fa fa-star text-primary"></small>
                                </div>
                                <p>{{ article.short_description }}</p>
                                <div class="d-flex justify-content-center mb-2">
                                    <a href="{% url 'article-detail-page' article_id=article.id %}"
                                       class="btn btn-sm btn-primary px-3 border-end"
                                       style="border-radius: 30px 0 0 30px;">Read More</a>
                                    <a data-article-id="{{ article.id }}"
                                       class="add-to-favorites-button btn btn-sm btn-primary px-3"
                                       style="border-radius: 0 30px 30px 0;">Add to favorites</a>

                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
            <!-- articles list end -->
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
            integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>
        $(document).ready(function () {
            $('.add-to-favorites-button').click(function () {
                var article_id = $(this).data('article-id');
                $.ajax({
                    type: 'POST',
                    url: '/add-to-favorites',
                    data: {'article_id': article_id, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                })
            })
        })
    </script>

{% endblock %}